name: github job
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking the current directory
        run: |
          pwd
          ls -lrth
          hostname
      - name: checking the source code
        uses: actions/checkout@v5
      - name: setting up nodejs
        uses: actions/setup-node@v3
      - name: installing dependencies
        run: |
          pwd
          ls -lrth
          hostname
